title: McCourt Physics
description: Personal website of Joseph McCourt, Ph.D. physicist at Argonne National Laboratory
url: https://www.mccourtphysics.com
author: Joseph McCourt

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .vscode
